from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from app.auth import require_admin
from app.config import get_settings
from app.db.models import (
    ConversationMessage,
    HandoffRequest,
    HandoffSession,
)
from app.db.session import get_db


router = APIRouter(tags=["live-handoff"])


class AdminMessageCreate(BaseModel):
    message: str = Field(min_length=1, max_length=8000)


@router.get("/api/chat/{conversation_id}/history")
def public_chat_history(
    conversation_id: str,
    db: Session = Depends(get_db),
):
    """
    Restore the visitor's full conversation after refresh/navigation.
    Conversation IDs are UUID-style opaque identifiers generated by the client/backend.
    """
    rows = (
        db.query(ConversationMessage)
        .filter(ConversationMessage.conversation_id == conversation_id)
        .order_by(ConversationMessage.id.asc())
        .all()
    )

    return {
        "conversation_id": conversation_id,
        "messages": [
            {
                "id": row.id,
                "role": row.role,
                "content": row.content,
                "created_at": row.created_at,
            }
            for row in rows
        ],
    }


@router.get("/api/chat/{conversation_id}/live")
def public_live_state(
    conversation_id: str,
    after_id: int = Query(default=0, ge=0),
    db: Session = Depends(get_db),
):
    session = (
        db.query(HandoffSession)
        .filter(HandoffSession.conversation_id == conversation_id)
        .first()
    )

    mode = session.mode if session else "bot"
    assigned_to = session.assigned_to if session else None

    rows = (
        db.query(ConversationMessage)
        .filter(
            ConversationMessage.conversation_id == conversation_id,
            ConversationMessage.id > after_id,
            ConversationMessage.role.in_(["agent", "system"]),
        )
        .order_by(ConversationMessage.id.asc())
        .all()
    )

    latest_row = (
        db.query(ConversationMessage)
        .filter(ConversationMessage.conversation_id == conversation_id)
        .order_by(ConversationMessage.id.desc())
        .first()
    )

    return {
        "mode": mode,
        "assigned_to": assigned_to,
        "last_message_id": latest_row.id if latest_row else after_id,
        "messages": [
            {
                "id": row.id,
                "role": row.role,
                "content": row.content,
                "created_at": row.created_at,
            }
            for row in rows
        ],
    }


@router.get(
    "/api/admin/handoff/queue",
    dependencies=[Depends(require_admin)],
)
def handoff_queue(db: Session = Depends(get_db)):
    rows = (
        db.query(HandoffSession)
        .filter(HandoffSession.mode == "pending_human")
        .order_by(HandoffSession.requested_at.asc())
        .all()
    )
    return [
        {
            "conversation_id": row.conversation_id,
            "visitor_name": row.visitor_name,
            "visitor_email": row.visitor_email,
            "reason": row.reason,
            "requested_at": row.requested_at,
            "mode": row.mode,
        }
        for row in rows
    ]


@router.get(
    "/api/admin/handoff/active",
    dependencies=[Depends(require_admin)],
)
def active_handoffs(db: Session = Depends(get_db)):
    username = get_settings().admin_username
    rows = (
        db.query(HandoffSession)
        .filter(
            HandoffSession.mode == "human",
            HandoffSession.assigned_to == username,
        )
        .order_by(HandoffSession.claimed_at.desc())
        .all()
    )
    return [
        {
            "conversation_id": row.conversation_id,
            "visitor_name": row.visitor_name,
            "visitor_email": row.visitor_email,
            "reason": row.reason,
            "mode": row.mode,
        }
        for row in rows
    ]


@router.post(
    "/api/admin/handoff/{conversation_id}/claim",
    dependencies=[Depends(require_admin)],
)
def claim_handoff(
    conversation_id: str,
    db: Session = Depends(get_db),
):
    username = get_settings().admin_username

    session = (
        db.query(HandoffSession)
        .filter(HandoffSession.conversation_id == conversation_id)
        .with_for_update()
        .first()
    )

    if not session:
        db.rollback()
        raise HTTPException(404, "Handoff conversation not found")

    if session.mode == "human":
        if session.assigned_to == username:
            db.rollback()
            return {
                "conversation_id": conversation_id,
                "mode": "human",
                "assigned_to": username,
                "already_claimed": True,
            }
        db.rollback()
        raise HTTPException(409, "Chat already claimed")

    if session.mode != "pending_human":
        db.rollback()
        raise HTTPException(409, "Chat is not waiting for a team member")

    session.mode = "human"
    session.assigned_to = username
    session.claimed_at = datetime.now(timezone.utc)

    request = (
        db.query(HandoffRequest)
        .filter(
            HandoffRequest.conversation_id == conversation_id,
            HandoffRequest.status == "pending",
        )
        .order_by(HandoffRequest.id.desc())
        .first()
    )
    if request:
        request.status = "claimed"

    db.add(
        ConversationMessage(
            conversation_id=conversation_id,
            role="system",
            content=f"{username} from Datamart has joined the live chat.",
        )
    )
    db.commit()

    return {
        "conversation_id": conversation_id,
        "mode": "human",
        "assigned_to": username,
        "already_claimed": False,
    }


@router.get(
    "/api/admin/handoff/{conversation_id}/messages",
    dependencies=[Depends(require_admin)],
)
def admin_handoff_messages(
    conversation_id: str,
    db: Session = Depends(get_db),
):
    session = (
        db.query(HandoffSession)
        .filter(HandoffSession.conversation_id == conversation_id)
        .first()
    )
    if not session:
        raise HTTPException(404, "Handoff conversation not found")

    rows = (
        db.query(ConversationMessage)
        .filter(ConversationMessage.conversation_id == conversation_id)
        .order_by(ConversationMessage.id.asc())
        .all()
    )

    return {
        "mode": session.mode,
        "visitor_name": session.visitor_name,
        "visitor_email": session.visitor_email,
        "assigned_to": session.assigned_to,
        "messages": [
            {
                "id": row.id,
                "role": row.role,
                "content": row.content,
                "created_at": row.created_at,
            }
            for row in rows
        ],
    }


@router.post(
    "/api/admin/handoff/{conversation_id}/message",
    dependencies=[Depends(require_admin)],
)
def admin_handoff_message(
    conversation_id: str,
    payload: AdminMessageCreate,
    db: Session = Depends(get_db),
):
    username = get_settings().admin_username

    session = (
        db.query(HandoffSession)
        .filter(HandoffSession.conversation_id == conversation_id)
        .first()
    )

    if not session:
        raise HTTPException(404, "Handoff conversation not found")

    if session.mode != "human" or session.assigned_to != username:
        raise HTTPException(403, "You have not claimed this chat")

    row = ConversationMessage(
        conversation_id=conversation_id,
        role="agent",
        content=payload.message.strip(),
    )
    db.add(row)
    db.commit()
    db.refresh(row)

    return {
        "id": row.id,
        "role": row.role,
        "content": row.content,
        "created_at": row.created_at,
    }


@router.post(
    "/api/admin/handoff/{conversation_id}/end",
    dependencies=[Depends(require_admin)],
)
def end_handoff(
    conversation_id: str,
    db: Session = Depends(get_db),
):
    username = get_settings().admin_username

    session = (
        db.query(HandoffSession)
        .filter(HandoffSession.conversation_id == conversation_id)
        .with_for_update()
        .first()
    )

    if not session:
        db.rollback()
        raise HTTPException(404, "Handoff conversation not found")

    if session.mode == "closed":
        db.rollback()
        return {"mode": "closed", "already_closed": True}

    if session.mode != "human" or session.assigned_to != username:
        db.rollback()
        raise HTTPException(403, "You are not assigned to this chat")

    session.mode = "closed"
    session.closed_at = datetime.now(timezone.utc)

    request = (
        db.query(HandoffRequest)
        .filter(HandoffRequest.conversation_id == conversation_id)
        .order_by(HandoffRequest.id.desc())
        .first()
    )
    if request:
        request.status = "closed"

    db.add(
        ConversationMessage(
            conversation_id=conversation_id,
            role="system",
            content=(
                "This live chat has ended. You can continue chatting with "
                "Datamart's AI assistant by sending a new message."
            ),
        )
    )
    db.commit()

    return {"mode": "closed", "already_closed": False}
